title: Robert Mohns
#author:
#  name: Robert Mohns
#  email: rmohns@mac.com
description: User Experience Professional in the Greater Boston area. I work with clients to devise and implement their digital marketing strategies, based on sound UX research, business strategy, and the latest web technologies. Also, I like cars, motorcycles, and building things.
theme: minima
  skin: solarized-dark
minima:
  social_links:
    twitter: bratling
    github:  rmohns
    instagram: bratling
  show_excerpts: true
  header_pages:
    - writing.md
    - about.md
