theme: minima
  skin: solarized-dark
title: Robert Mohns
description: User Experience Professional in the Greater Boston area. I work with clients to devise and implement their digital marketing strategies, based on sound UX research, business strategy, and the latest web technologies. Also, I like cars, motorcycles, and building things.
author:
  name: Robert Mohns
  email: rmohns@mac.com
minima:
  social_links:
    twitter: bratling
    github:  rmohns
    instagram: bratling
show_excerpts: true